"""sync_user_model

Revision ID: 07fbc5ed5a0e
Revises: cbbdee27828a
Create Date: 2026-02-06 20:12:17.067402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07fbc5ed5a0e'
down_revision: Union[str, None] = 'cbbdee27828a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon', 'prize_pool')
    op.drop_column('project', 'cover_image')
    op.drop_column('user', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume', sa.VARCHAR(), nullable=True))
    op.add_column('project', sa.Column('cover_image', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('prize_pool', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
