"""add_flow_models

Revision ID: 52a3c62d0a31
Revises: 65eca11b5a47
Create Date: 2026-01-30 10:33:22.014043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52a3c62d0a31'
down_revision: Union[str, None] = '65eca11b5a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='enrollmentstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('appointed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hackathon', sa.Column('registration_start_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('registration_end_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('submission_start_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('submission_end_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ONGOING', 'ENDED', name='hackathonstatus'), nullable=False, server_default='DRAFT'))
    op.add_column('project', sa.Column('status', sa.Enum('SUBMITTED', 'GRADING', 'GRADED', name='projectstatus'), nullable=False, server_default='SUBMITTED'))
    op.add_column('project', sa.Column('total_score', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_column('project', 'total_score')
    op.drop_column('project', 'status')
    op.drop_column('hackathon', 'status')
    op.drop_column('hackathon', 'submission_end_date')
    op.drop_column('hackathon', 'submission_start_date')
    op.drop_column('hackathon', 'registration_end_date')
    op.drop_column('hackathon', 'registration_start_date')
    op.drop_table('score')
    op.drop_table('judge')
    op.drop_table('enrollment')
    # ### end Alembic commands ###
