"""add hackathon sponsors detail

Revision ID: eb69f6288567
Revises: f2e609b7a887
Create Date: 2026-02-10 05:12:21.064240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb69f6288567'
down_revision: Union[str, None] = 'f2e609b7a887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('sponsors_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon', 'sponsors_detail')
    # ### end Alembic commands ###
