"""add_project_attachment

Revision ID: 2a66cf70fcf5
Revises: 7c8f40be19ac
Create Date: 2026-01-30 13:26:10.531344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a66cf70fcf5'
down_revision: Union[str, None] = '7c8f40be19ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'attachment_url')
    # ### end Alembic commands ###
