"""add_hackathon_fields

Revision ID: 456d9dc43343
Revises: 08a0d0fbecf7
Create Date: 2026-01-30 12:39:29.712315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '456d9dc43343'
down_revision: Union[str, None] = '08a0d0fbecf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('organizer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('theme_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('level_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('judging_start_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('judging_end_date', sa.DateTime(), nullable=True))
    op.add_column('hackathon', sa.Column('awards', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('judging_dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon', 'judging_dimensions')
    op.drop_column('hackathon', 'rules')
    op.drop_column('hackathon', 'awards')
    op.drop_column('hackathon', 'judging_end_date')
    op.drop_column('hackathon', 'judging_start_date')
    op.drop_column('hackathon', 'level_tags')
    op.drop_column('hackathon', 'theme_tags')
    op.drop_column('hackathon', 'organizer_name')
    op.drop_column('hackathon', 'cover')
    # ### end Alembic commands ###
