"""add_score_details

Revision ID: 63fff62c6f73
Revises: 38579bf8d6f3
Create Date: 2026-02-09 23:17:53.532090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63fff62c6f73'
down_revision: Union[str, None] = '38579bf8d6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'details')
    # ### end Alembic commands ###
