"""Add wechat fields and verification code

Revision ID: b5fecd3d949e
Revises: a09f4c9ba40f
Create Date: 2026-01-30 11:22:28.771046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5fecd3d949e'
down_revision: Union[str, None] = 'a09f4c9ba40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationcode_email'), 'verificationcode', ['email'], unique=False)
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wx_openid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('wx_unionid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('wx_test_openid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_user_wx_openid'), ['wx_openid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_wx_test_openid'), ['wx_test_openid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_wx_unionid'), ['wx_unionid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wx_unionid'))
        batch_op.drop_index(batch_op.f('ix_user_wx_test_openid'))
        batch_op.drop_index(batch_op.f('ix_user_wx_openid'))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('nickname')
        batch_op.drop_column('wx_test_openid')
        batch_op.drop_column('wx_unionid')
        batch_op.drop_column('wx_openid')
    
    op.drop_index(op.f('ix_verificationcode_email'), table_name='verificationcode')
    op.drop_table('verificationcode')
    # ### end Alembic commands ###
