"""add tech_stack to project

Revision ID: fdab8014c1ce
Revises: d8c6887ec4eb
Create Date: 2026-02-10 19:26:30.057875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdab8014c1ce'
down_revision: Union[str, None] = 'd8c6887ec4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'tech_stack')
    # ### end Alembic commands ###
