"""ensure_wechat_fields

Revision ID: 08a0d0fbecf7
Revises: b5fecd3d949e
Create Date: 2026-01-30 11:45:28.916975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08a0d0fbecf7'
down_revision: Union[str, None] = 'b5fecd3d949e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
