"""add_hackathon_resource_detail

Revision ID: 38579bf8d6f3
Revises: ae366ee0dd5e
Create Date: 2026-02-07 09:38:24.832046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38579bf8d6f3'
down_revision: Union[str, None] = 'ae366ee0dd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('resource_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_image')
    op.drop_column('hackathon', 'resource_detail')
    # ### end Alembic commands ###
