"""add_hackathon_fields

Revision ID: 84470c14afdb
Revises: 456d9dc43343
Create Date: 2026-01-30 13:09:49.006333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84470c14afdb'
down_revision: Union[str, None] = '456d9dc43343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('professionalism_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('awards_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('rules_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('scoring_dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('hackathon', 'judging_dimensions')
    op.drop_column('hackathon', 'awards')
    op.drop_column('hackathon', 'organizer_name')
    op.drop_column('hackathon', 'cover')
    op.drop_column('hackathon', 'rules')
    op.drop_column('hackathon', 'level_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('level_tags', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('rules', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('cover', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('organizer_name', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('awards', sa.VARCHAR(), nullable=True))
    op.add_column('hackathon', sa.Column('judging_dimensions', sa.VARCHAR(), nullable=True))
    op.drop_column('hackathon', 'scoring_dimensions')
    op.drop_column('hackathon', 'rules_detail')
    op.drop_column('hackathon', 'awards_detail')
    op.drop_column('hackathon', 'professionalism_tags')
    op.drop_column('hackathon', 'cover_image')
    # ### end Alembic commands ###
