"""add_hackathon_details

Revision ID: ae366ee0dd5e
Revises: 07fbc5ed5a0e
Create Date: 2026-02-06 20:17:56.940243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae366ee0dd5e'
down_revision: Union[str, None] = '07fbc5ed5a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('hackathon', sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('registration_type', sa.Enum('INDIVIDUAL', 'TEAM', name='registrationtype'), nullable=False, server_default='TEAM'))
    op.add_column('hackathon', sa.Column('format', sa.Enum('ONLINE', 'OFFLINE', name='hackathonformat'), nullable=False, server_default='ONLINE'))
    op.add_column('hackathon', sa.Column('organizer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('contact_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hackathon', sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon', 'requirements')
    op.drop_column('hackathon', 'contact_info')
    op.drop_column('hackathon', 'organizer_name')
    op.drop_column('hackathon', 'format')
    op.drop_column('hackathon', 'registration_type')
    op.drop_column('hackathon', 'subtitle')
    # ### end Alembic commands ###
