"""add_user_city_phone_project_cover_hackathon_prize

Revision ID: cbbdee27828a
Revises: 0db7f357d19b
Create Date: 2026-02-06 19:29:25.298993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbbdee27828a'
down_revision: Union[str, None] = '0db7f357d19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_image')
    # ### end Alembic commands ###
